name: webhooks

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Version tags"
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Distribution
        uses: appleboy/ssh-action@master
        with:
          host: 139.199.30.36
          port: 22
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: cd /data/xii &&ls -a
